- id: bandit
  name: bandit
  description: Bandit is a tool for finding common security issues in Python code
  entry: bandit
  language: python
  language_version: python3
  types: [python]
- id: mypy
  name: mypy
  entry: mypy
  language: python
  types_or: [python, pyi]
  args: [--ignore-missing-imports, --scripts-are-modules]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
# TODO: remove if the dependencies conflict cannot be resolved
# - id: prospector
#   name: prospector
#   description: Prospector is a tool to analyse Python code and output information about errors, potential problems, convention violations and complexity
#   entry: prospector
#   language: python
#   types: [python]
- id: hadolint-docker
  name: Lint Dockerfiles
  description: Runs hadolint Docker image to lint Dockerfiles
  language: docker_image
  types: [dockerfile]
  entry: hadolint/hadolint:v2.8.0 hadolint
