version: "3.9"

services:
  publisher:
    image: marekbryling/suttapublisher:prev_development
    env_file:
      - ./.env_public
    volumes:
      - ./sutta_publisher/src:/app
      - ./sutta_publisher/tests:/tests
      - ./tmp:/tmp
    environment:
      - PYTHONDEBUG=1
      - PYTHONLOGLEVEL=DEBUG
    network_mode: host
