version: "3.9"

services:
  publisher:
    build:
      context: sutta_publisher
      target: development
    volumes:
      - ./sutta_publisher/src:/app
      - ./sutta_publisher/tests:/tests
    network_mode: host