version: "3.9"

services:
  publisher:
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile
    container_name: sutta_publisher
    network_mode: host
    volumes:
      - ../../out:/app/out
