version: "3.9"

services:
  publisher:
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile.dev
    container_name: sutta_publisher_dev
    network_mode: host
    volumes:
      - ../..:/app
