name: Autodiscover and Update Publications

on:
  schedule:
    cron: '0 0 * * MON'

env:
  API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run SuttaPublisher
        run: make run $API_TOKEN
