name: Generate and Push Publications

on:
  workflow_dispatch:
    inputs:
      publication_ids:
        description: 'Publication IDs (comma-separated)'
        required: false

env:
  PUBLICATION_IDS: ${{ github.event.inputs.publication_ids }}
  API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run SuttaPublisher
        run: make run $API_TOKEN $PUBLICATION_IDS
