name: Generate and publish edition

on:
  workflow_dispatch:
    inputs:
      publication_ids:
        description: 'IDs of publications'     
        required: true
 
env:
  BOT_API_KEY: ${{ secrets.SC_BOT_KEY }}

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Publication IDs: ${{ github.event.inputs.publication_ids }}"
