name: Generate and publish edition

on:
  workflow_dispatch:
    inputs:
      publication_id:
        description: 'IDs of publications'
        required: true

env:
  PUBLICATION_ID: ${{ github.event.inputs.publication_id }}

jobs:
  generate_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run SuttaPublisher
        run: make run $PUBLICATION_ID ${{ secrets.GITHUB_TOKEN }}
